# Generated by Django 5.2.1 on 2025-05-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='id',
        ),
        migrations.AlterField(
            model_name='note',
            name='noteId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
