# Generated by Django 5.2.1 on 2025-05-19 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0002_remove_note_id_alter_note_noteid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='noteDescription',
            new_name='note',
        ),
    ]
