# Generated by Django 5.0.14 on 2025-05-29 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autores',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='libros',
            options={'managed': False},
        ),
    ]
